#!/usr/bin/env bash
# A bash script that installs Nginx on web-01

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart