#!/usr/bin/env bash
# A bash script that installs Nginx on web-01 and configures redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
