#!/usr/bin/env bash
# A script that install a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend sodiqtechcode
    bind *:80
    mode http
    default_backend sod

backend sod
    balance roundrobin
    server 221460-web-01 54.89.118.186:80 check
    server 221460-web-02 3.83.245.19:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
