#!/bin/env bash

# Get all active IPv4 addresses
ipv4_addresses=$(ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")

# Display the IPv4 addresses
echo "Active IPv4 addresses:"
echo "$ipv4_addresses"

