#!/usr/bin/env bash
# A bash script that get Apache to run on the container
# and to return a page containing Hello Holberton

sudo apt-get update -y
apt-get -y install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
