#!/usr/bin/env bash
# Automated setup for Docker installation and configuration

apt-get update
apt-get -y install docker.io
ln -sf /usr/bin/docker.io /usr/local/bin/docker
sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
update-rc.d docker.io defaults
docker pull ubuntu
docker run -i -t ubuntu /bin/bash
echo "Docker setup complete."

